services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./src:/app/src
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - MODEL_NAME=LogisticRegression_multinomial.pkl
    command: flask run --host=0.0.0.0 --port=5000
    restart: unless-stopped 
